site_name: Modding with Kiwi
repo_url: https://github.com/Snownee/ModdingWithKiwi
site_author: Snownee
nav:
    - 前言: README.md
    - 模块系统: module.md
    - 自动注册: registry.md
    - 实用类:
        - NBTHelper: utils/nbthelper.md
        - 杂项: utils/util.md
    - 物品 / 方块拓展: item-block.md
    - TileEntity: tileentity.md
    - 网络: network.md
    - 配方:
        - 条件：模块加载: recipe/module-loaded.md
        - 配方：消耗容器: recipe/no-containers.md
        - 动态配方: recipe/dynamic.md
    - 可变材质方块:
        - 可变材质方块: textureable/README.md
        - 合成配方: textureable/crafting.md
    - 任务系统: schedule.md
    - 内置命令: command.md
    - 调试功能: debug.md

theme:
    name: readthedocs
