site_name: Modding with Kiwi
repo_name: ModdingWithKiwi
repo_url: https://github.com/Snownee/ModdingWithKiwi
site_author: Snownee

nav:
    - 前言: README.md
    - 模块系统: module.md
    - 自动注册: registry.md
    - 实用类:
        - NBTHelper: utils/nbthelper.md
        - 推迟任务: utils/deferred-actions.md
        - 杂项: utils/util.md
    - 物品 / 方块拓展: item-block.md
    - 注解式配置文件: config.md
    - TileEntity: tileentity.md
    - 网络: network.md
    - 配方:
        - 条件：模块加载: recipe/module-loaded.md
        - 配方：消耗容器: recipe/no-containers.md
        - 动态配方: recipe/dynamic.md
        - 新的配方类型: recipe/new-type.md
        - 流体Ingredient: recipe/fluid-ingredient.md
    - 可变材质方块:
        - 可变材质方块: textureable/README.md
        - 合成配方: textureable/crafting.md
    - 计划任务: schedule.md
    - 内置命令: command.md
    - 调试功能: debug.md
    - 贡献者奖励:
        - 贡献者奖励: contributors/README.md
        - ITierProvider: contributors/provider.md
        - 添加效果: contributors/renderer.md

theme:
    name: material

 language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search
  - awesome-pages