site_name: Modding with Kiwi
repo_name: ModdingWithKiwi
repo_url: https://github.com/Snownee/ModdingWithKiwi
site_author: Snownee

nav:
    - 前言: README.md
    - 模块系统: module.md
    - 自动注册: registry.md
    - 实用类:
        - Platform: utils/platform.md
        - NBTHelper: utils/nbthelper.md
        - 原版操作: utils/vanilla-actions.md
        - 杂项: utils/util.md
    - 物品 / 方块拓展: item-block.md
    - 注解式配置文件: config.md
    - BlockEntity: blockentity.md
    - 网络: network.md
    - 数据生成:
        - 战利品表: datagen/loot.md
        - 配方: datagen/recipes.md
        - 标签: datagen/tags.md
    - 配方:
        - 原料：替代方案: recipe/alternatives.md
        - 条件：模块加载: recipe/module-loaded.md
        - 条件：解析原料: recipe/try-parse.md
        - 配方：消耗容器: recipe/no-containers.md
        - 动态配方: recipe/dynamic.md
        - 新的配方类型: recipe/new-type.md
    - 可变贴图方块:
        - 可变贴图方块: retexture/README.md
        - 合成配方: retexture/crafting.md
    - 计划任务: schedule.md
    - 内置命令: command.md
    - 调试功能: debug.md
    - 贡献者奖励: contributors.md

theme:
    name: material
    language: zh
    features:
        - content.code.annotate
        - content.tabs.link
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.progressbar
    - pymdownx.saneheaders
    - pymdownx.smartsymbols
    - pymdownx.snippets:
        base_path: docs
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

plugins:
  - search
  - awesome-pages